// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcs_mcs_events.proto

package com.tmt.tcs.mcs.protos;

public final class TcsMcsEventsProtos {
  private TcsMcsEventsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TcsPositionDemandEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eventpoc.TcsPositionDemandEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double azimuth = 1;</code>
     *
     * <pre>
     * azimuth position
     * </pre>
     */
    boolean hasAzimuth();
    /**
     * <code>required double azimuth = 1;</code>
     *
     * <pre>
     * azimuth position
     * </pre>
     */
    double getAzimuth();

    /**
     * <code>required double elevation = 2;</code>
     *
     * <pre>
     * elevation position
     * </pre>
     */
    boolean hasElevation();
    /**
     * <code>required double elevation = 2;</code>
     *
     * <pre>
     * elevation position
     * </pre>
     */
    double getElevation();

    /**
     * <code>required double time = 3;</code>
     *
     * <pre>
     * time at which event sampled
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required double time = 3;</code>
     *
     * <pre>
     * time at which event sampled
     * </pre>
     */
    double getTime();
  }
  /**
   * Protobuf type {@code eventpoc.TcsPositionDemandEvent}
   */
  public static final class TcsPositionDemandEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eventpoc.TcsPositionDemandEvent)
      TcsPositionDemandEventOrBuilder {
    // Use TcsPositionDemandEvent.newBuilder() to construct.
    private TcsPositionDemandEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TcsPositionDemandEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TcsPositionDemandEvent defaultInstance;
    public static TcsPositionDemandEvent getDefaultInstance() {
      return defaultInstance;
    }

    public TcsPositionDemandEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TcsPositionDemandEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              azimuth_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              elevation_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              time_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_TcsPositionDemandEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_TcsPositionDemandEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.class, com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<TcsPositionDemandEvent> PARSER =
        new com.google.protobuf.AbstractParser<TcsPositionDemandEvent>() {
      public TcsPositionDemandEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TcsPositionDemandEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TcsPositionDemandEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AZIMUTH_FIELD_NUMBER = 1;
    private double azimuth_;
    /**
     * <code>required double azimuth = 1;</code>
     *
     * <pre>
     * azimuth position
     * </pre>
     */
    public boolean hasAzimuth() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double azimuth = 1;</code>
     *
     * <pre>
     * azimuth position
     * </pre>
     */
    public double getAzimuth() {
      return azimuth_;
    }

    public static final int ELEVATION_FIELD_NUMBER = 2;
    private double elevation_;
    /**
     * <code>required double elevation = 2;</code>
     *
     * <pre>
     * elevation position
     * </pre>
     */
    public boolean hasElevation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double elevation = 2;</code>
     *
     * <pre>
     * elevation position
     * </pre>
     */
    public double getElevation() {
      return elevation_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private double time_;
    /**
     * <code>required double time = 3;</code>
     *
     * <pre>
     * time at which event sampled
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double time = 3;</code>
     *
     * <pre>
     * time at which event sampled
     * </pre>
     */
    public double getTime() {
      return time_;
    }

    private void initFields() {
      azimuth_ = 0D;
      elevation_ = 0D;
      time_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAzimuth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElevation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, azimuth_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, elevation_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, azimuth_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, elevation_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eventpoc.TcsPositionDemandEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eventpoc.TcsPositionDemandEvent)
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_TcsPositionDemandEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_TcsPositionDemandEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.class, com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.Builder.class);
      }

      // Construct using com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        azimuth_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        elevation_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_TcsPositionDemandEvent_descriptor;
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent getDefaultInstanceForType() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.getDefaultInstance();
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent build() {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent buildPartial() {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent result = new com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.azimuth_ = azimuth_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.elevation_ = elevation_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent) {
          return mergeFrom((com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent other) {
        if (other == com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent.getDefaultInstance()) return this;
        if (other.hasAzimuth()) {
          setAzimuth(other.getAzimuth());
        }
        if (other.hasElevation()) {
          setElevation(other.getElevation());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAzimuth()) {
          
          return false;
        }
        if (!hasElevation()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.TcsPositionDemandEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double azimuth_ ;
      /**
       * <code>required double azimuth = 1;</code>
       *
       * <pre>
       * azimuth position
       * </pre>
       */
      public boolean hasAzimuth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double azimuth = 1;</code>
       *
       * <pre>
       * azimuth position
       * </pre>
       */
      public double getAzimuth() {
        return azimuth_;
      }
      /**
       * <code>required double azimuth = 1;</code>
       *
       * <pre>
       * azimuth position
       * </pre>
       */
      public Builder setAzimuth(double value) {
        bitField0_ |= 0x00000001;
        azimuth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double azimuth = 1;</code>
       *
       * <pre>
       * azimuth position
       * </pre>
       */
      public Builder clearAzimuth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        azimuth_ = 0D;
        onChanged();
        return this;
      }

      private double elevation_ ;
      /**
       * <code>required double elevation = 2;</code>
       *
       * <pre>
       * elevation position
       * </pre>
       */
      public boolean hasElevation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double elevation = 2;</code>
       *
       * <pre>
       * elevation position
       * </pre>
       */
      public double getElevation() {
        return elevation_;
      }
      /**
       * <code>required double elevation = 2;</code>
       *
       * <pre>
       * elevation position
       * </pre>
       */
      public Builder setElevation(double value) {
        bitField0_ |= 0x00000002;
        elevation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elevation = 2;</code>
       *
       * <pre>
       * elevation position
       * </pre>
       */
      public Builder clearElevation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        elevation_ = 0D;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>required double time = 3;</code>
       *
       * <pre>
       * time at which event sampled
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double time = 3;</code>
       *
       * <pre>
       * time at which event sampled
       * </pre>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 3;</code>
       *
       * <pre>
       * time at which event sampled
       * </pre>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 3;</code>
       *
       * <pre>
       * time at which event sampled
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eventpoc.TcsPositionDemandEvent)
    }

    static {
      defaultInstance = new TcsPositionDemandEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eventpoc.TcsPositionDemandEvent)
  }

  public interface McsCurrentPositionEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eventpoc.McsCurrentPositionEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool mcsInPosition = 1;</code>
     *
     * <pre>
     * conjunction of azInPosition and elInPosition
     * </pre>
     */
    boolean hasMcsInPosition();
    /**
     * <code>required bool mcsInPosition = 1;</code>
     *
     * <pre>
     * conjunction of azInPosition and elInPosition
     * </pre>
     */
    boolean getMcsInPosition();

    /**
     * <code>required double azPos = 2;</code>
     */
    boolean hasAzPos();
    /**
     * <code>required double azPos = 2;</code>
     */
    double getAzPos();

    /**
     * <code>required double azPosDemand = 3;</code>
     */
    boolean hasAzPosDemand();
    /**
     * <code>required double azPosDemand = 3;</code>
     */
    double getAzPosDemand();

    /**
     * <code>required double azPosError = 4;</code>
     */
    boolean hasAzPosError();
    /**
     * <code>required double azPosError = 4;</code>
     */
    double getAzPosError();

    /**
     * <code>required bool azInPosition = 5;</code>
     */
    boolean hasAzInPosition();
    /**
     * <code>required bool azInPosition = 5;</code>
     */
    boolean getAzInPosition();

    /**
     * <code>required double elPos = 6;</code>
     */
    boolean hasElPos();
    /**
     * <code>required double elPos = 6;</code>
     */
    double getElPos();

    /**
     * <code>required double elPosDemand = 7;</code>
     */
    boolean hasElPosDemand();
    /**
     * <code>required double elPosDemand = 7;</code>
     */
    double getElPosDemand();

    /**
     * <code>required double elPosError = 8;</code>
     */
    boolean hasElPosError();
    /**
     * <code>required double elPosError = 8;</code>
     */
    double getElPosError();

    /**
     * <code>required bool elInPosition = 9;</code>
     */
    boolean hasElInPosition();
    /**
     * <code>required bool elInPosition = 9;</code>
     */
    boolean getElInPosition();

    /**
     * <code>required double encodeLatchingTime = 10;</code>
     */
    boolean hasEncodeLatchingTime();
    /**
     * <code>required double encodeLatchingTime = 10;</code>
     */
    double getEncodeLatchingTime();

    /**
     * <code>required int32 azPosDmdErrCount = 11;</code>
     */
    boolean hasAzPosDmdErrCount();
    /**
     * <code>required int32 azPosDmdErrCount = 11;</code>
     */
    int getAzPosDmdErrCount();

    /**
     * <code>required int32 elPosDmdErrCount = 12;</code>
     */
    boolean hasElPosDmdErrCount();
    /**
     * <code>required int32 elPosDmdErrCount = 12;</code>
     */
    int getElPosDmdErrCount();

    /**
     * <code>required double time = 13;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 13;</code>
     */
    double getTime();
  }
  /**
   * Protobuf type {@code eventpoc.McsCurrentPositionEvent}
   */
  public static final class McsCurrentPositionEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eventpoc.McsCurrentPositionEvent)
      McsCurrentPositionEventOrBuilder {
    // Use McsCurrentPositionEvent.newBuilder() to construct.
    private McsCurrentPositionEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private McsCurrentPositionEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final McsCurrentPositionEvent defaultInstance;
    public static McsCurrentPositionEvent getDefaultInstance() {
      return defaultInstance;
    }

    public McsCurrentPositionEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private McsCurrentPositionEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mcsInPosition_ = input.readBool();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              azPos_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              azPosDemand_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              azPosError_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              azInPosition_ = input.readBool();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              elPos_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              elPosDemand_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              elPosError_ = input.readDouble();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              elInPosition_ = input.readBool();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              encodeLatchingTime_ = input.readDouble();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              azPosDmdErrCount_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              elPosDmdErrCount_ = input.readInt32();
              break;
            }
            case 105: {
              bitField0_ |= 0x00001000;
              time_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_McsCurrentPositionEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_McsCurrentPositionEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.class, com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<McsCurrentPositionEvent> PARSER =
        new com.google.protobuf.AbstractParser<McsCurrentPositionEvent>() {
      public McsCurrentPositionEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new McsCurrentPositionEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<McsCurrentPositionEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MCSINPOSITION_FIELD_NUMBER = 1;
    private boolean mcsInPosition_;
    /**
     * <code>required bool mcsInPosition = 1;</code>
     *
     * <pre>
     * conjunction of azInPosition and elInPosition
     * </pre>
     */
    public boolean hasMcsInPosition() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool mcsInPosition = 1;</code>
     *
     * <pre>
     * conjunction of azInPosition and elInPosition
     * </pre>
     */
    public boolean getMcsInPosition() {
      return mcsInPosition_;
    }

    public static final int AZPOS_FIELD_NUMBER = 2;
    private double azPos_;
    /**
     * <code>required double azPos = 2;</code>
     */
    public boolean hasAzPos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double azPos = 2;</code>
     */
    public double getAzPos() {
      return azPos_;
    }

    public static final int AZPOSDEMAND_FIELD_NUMBER = 3;
    private double azPosDemand_;
    /**
     * <code>required double azPosDemand = 3;</code>
     */
    public boolean hasAzPosDemand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double azPosDemand = 3;</code>
     */
    public double getAzPosDemand() {
      return azPosDemand_;
    }

    public static final int AZPOSERROR_FIELD_NUMBER = 4;
    private double azPosError_;
    /**
     * <code>required double azPosError = 4;</code>
     */
    public boolean hasAzPosError() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double azPosError = 4;</code>
     */
    public double getAzPosError() {
      return azPosError_;
    }

    public static final int AZINPOSITION_FIELD_NUMBER = 5;
    private boolean azInPosition_;
    /**
     * <code>required bool azInPosition = 5;</code>
     */
    public boolean hasAzInPosition() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool azInPosition = 5;</code>
     */
    public boolean getAzInPosition() {
      return azInPosition_;
    }

    public static final int ELPOS_FIELD_NUMBER = 6;
    private double elPos_;
    /**
     * <code>required double elPos = 6;</code>
     */
    public boolean hasElPos() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required double elPos = 6;</code>
     */
    public double getElPos() {
      return elPos_;
    }

    public static final int ELPOSDEMAND_FIELD_NUMBER = 7;
    private double elPosDemand_;
    /**
     * <code>required double elPosDemand = 7;</code>
     */
    public boolean hasElPosDemand() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double elPosDemand = 7;</code>
     */
    public double getElPosDemand() {
      return elPosDemand_;
    }

    public static final int ELPOSERROR_FIELD_NUMBER = 8;
    private double elPosError_;
    /**
     * <code>required double elPosError = 8;</code>
     */
    public boolean hasElPosError() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required double elPosError = 8;</code>
     */
    public double getElPosError() {
      return elPosError_;
    }

    public static final int ELINPOSITION_FIELD_NUMBER = 9;
    private boolean elInPosition_;
    /**
     * <code>required bool elInPosition = 9;</code>
     */
    public boolean hasElInPosition() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required bool elInPosition = 9;</code>
     */
    public boolean getElInPosition() {
      return elInPosition_;
    }

    public static final int ENCODELATCHINGTIME_FIELD_NUMBER = 10;
    private double encodeLatchingTime_;
    /**
     * <code>required double encodeLatchingTime = 10;</code>
     */
    public boolean hasEncodeLatchingTime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required double encodeLatchingTime = 10;</code>
     */
    public double getEncodeLatchingTime() {
      return encodeLatchingTime_;
    }

    public static final int AZPOSDMDERRCOUNT_FIELD_NUMBER = 11;
    private int azPosDmdErrCount_;
    /**
     * <code>required int32 azPosDmdErrCount = 11;</code>
     */
    public boolean hasAzPosDmdErrCount() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 azPosDmdErrCount = 11;</code>
     */
    public int getAzPosDmdErrCount() {
      return azPosDmdErrCount_;
    }

    public static final int ELPOSDMDERRCOUNT_FIELD_NUMBER = 12;
    private int elPosDmdErrCount_;
    /**
     * <code>required int32 elPosDmdErrCount = 12;</code>
     */
    public boolean hasElPosDmdErrCount() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 elPosDmdErrCount = 12;</code>
     */
    public int getElPosDmdErrCount() {
      return elPosDmdErrCount_;
    }

    public static final int TIME_FIELD_NUMBER = 13;
    private double time_;
    /**
     * <code>required double time = 13;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required double time = 13;</code>
     */
    public double getTime() {
      return time_;
    }

    private void initFields() {
      mcsInPosition_ = false;
      azPos_ = 0D;
      azPosDemand_ = 0D;
      azPosError_ = 0D;
      azInPosition_ = false;
      elPos_ = 0D;
      elPosDemand_ = 0D;
      elPosError_ = 0D;
      elInPosition_ = false;
      encodeLatchingTime_ = 0D;
      azPosDmdErrCount_ = 0;
      elPosDmdErrCount_ = 0;
      time_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMcsInPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAzPos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAzPosDemand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAzPosError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAzInPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElPos()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElPosDemand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElPosError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElInPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncodeLatchingTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAzPosDmdErrCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElPosDmdErrCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, mcsInPosition_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, azPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, azPosDemand_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, azPosError_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, azInPosition_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, elPos_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, elPosDemand_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, elPosError_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, elInPosition_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, encodeLatchingTime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, azPosDmdErrCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, elPosDmdErrCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeDouble(13, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, mcsInPosition_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, azPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, azPosDemand_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, azPosError_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, azInPosition_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, elPos_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, elPosDemand_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, elPosError_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, elInPosition_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, encodeLatchingTime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, azPosDmdErrCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, elPosDmdErrCount_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eventpoc.McsCurrentPositionEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eventpoc.McsCurrentPositionEvent)
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_McsCurrentPositionEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_McsCurrentPositionEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.class, com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.Builder.class);
      }

      // Construct using com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mcsInPosition_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        azPos_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        azPosDemand_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        azPosError_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        azInPosition_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        elPos_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        elPosDemand_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        elPosError_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        elInPosition_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        encodeLatchingTime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        azPosDmdErrCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        elPosDmdErrCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.internal_static_eventpoc_McsCurrentPositionEvent_descriptor;
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent getDefaultInstanceForType() {
        return com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.getDefaultInstance();
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent build() {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent buildPartial() {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent result = new com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mcsInPosition_ = mcsInPosition_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.azPos_ = azPos_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.azPosDemand_ = azPosDemand_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.azPosError_ = azPosError_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.azInPosition_ = azInPosition_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.elPos_ = elPos_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.elPosDemand_ = elPosDemand_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.elPosError_ = elPosError_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.elInPosition_ = elInPosition_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.encodeLatchingTime_ = encodeLatchingTime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.azPosDmdErrCount_ = azPosDmdErrCount_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.elPosDmdErrCount_ = elPosDmdErrCount_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent) {
          return mergeFrom((com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent other) {
        if (other == com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent.getDefaultInstance()) return this;
        if (other.hasMcsInPosition()) {
          setMcsInPosition(other.getMcsInPosition());
        }
        if (other.hasAzPos()) {
          setAzPos(other.getAzPos());
        }
        if (other.hasAzPosDemand()) {
          setAzPosDemand(other.getAzPosDemand());
        }
        if (other.hasAzPosError()) {
          setAzPosError(other.getAzPosError());
        }
        if (other.hasAzInPosition()) {
          setAzInPosition(other.getAzInPosition());
        }
        if (other.hasElPos()) {
          setElPos(other.getElPos());
        }
        if (other.hasElPosDemand()) {
          setElPosDemand(other.getElPosDemand());
        }
        if (other.hasElPosError()) {
          setElPosError(other.getElPosError());
        }
        if (other.hasElInPosition()) {
          setElInPosition(other.getElInPosition());
        }
        if (other.hasEncodeLatchingTime()) {
          setEncodeLatchingTime(other.getEncodeLatchingTime());
        }
        if (other.hasAzPosDmdErrCount()) {
          setAzPosDmdErrCount(other.getAzPosDmdErrCount());
        }
        if (other.hasElPosDmdErrCount()) {
          setElPosDmdErrCount(other.getElPosDmdErrCount());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMcsInPosition()) {
          
          return false;
        }
        if (!hasAzPos()) {
          
          return false;
        }
        if (!hasAzPosDemand()) {
          
          return false;
        }
        if (!hasAzPosError()) {
          
          return false;
        }
        if (!hasAzInPosition()) {
          
          return false;
        }
        if (!hasElPos()) {
          
          return false;
        }
        if (!hasElPosDemand()) {
          
          return false;
        }
        if (!hasElPosError()) {
          
          return false;
        }
        if (!hasElInPosition()) {
          
          return false;
        }
        if (!hasEncodeLatchingTime()) {
          
          return false;
        }
        if (!hasAzPosDmdErrCount()) {
          
          return false;
        }
        if (!hasElPosDmdErrCount()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tmt.tcs.mcs.protos.TcsMcsEventsProtos.McsCurrentPositionEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean mcsInPosition_ ;
      /**
       * <code>required bool mcsInPosition = 1;</code>
       *
       * <pre>
       * conjunction of azInPosition and elInPosition
       * </pre>
       */
      public boolean hasMcsInPosition() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool mcsInPosition = 1;</code>
       *
       * <pre>
       * conjunction of azInPosition and elInPosition
       * </pre>
       */
      public boolean getMcsInPosition() {
        return mcsInPosition_;
      }
      /**
       * <code>required bool mcsInPosition = 1;</code>
       *
       * <pre>
       * conjunction of azInPosition and elInPosition
       * </pre>
       */
      public Builder setMcsInPosition(boolean value) {
        bitField0_ |= 0x00000001;
        mcsInPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool mcsInPosition = 1;</code>
       *
       * <pre>
       * conjunction of azInPosition and elInPosition
       * </pre>
       */
      public Builder clearMcsInPosition() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mcsInPosition_ = false;
        onChanged();
        return this;
      }

      private double azPos_ ;
      /**
       * <code>required double azPos = 2;</code>
       */
      public boolean hasAzPos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double azPos = 2;</code>
       */
      public double getAzPos() {
        return azPos_;
      }
      /**
       * <code>required double azPos = 2;</code>
       */
      public Builder setAzPos(double value) {
        bitField0_ |= 0x00000002;
        azPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double azPos = 2;</code>
       */
      public Builder clearAzPos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        azPos_ = 0D;
        onChanged();
        return this;
      }

      private double azPosDemand_ ;
      /**
       * <code>required double azPosDemand = 3;</code>
       */
      public boolean hasAzPosDemand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double azPosDemand = 3;</code>
       */
      public double getAzPosDemand() {
        return azPosDemand_;
      }
      /**
       * <code>required double azPosDemand = 3;</code>
       */
      public Builder setAzPosDemand(double value) {
        bitField0_ |= 0x00000004;
        azPosDemand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double azPosDemand = 3;</code>
       */
      public Builder clearAzPosDemand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        azPosDemand_ = 0D;
        onChanged();
        return this;
      }

      private double azPosError_ ;
      /**
       * <code>required double azPosError = 4;</code>
       */
      public boolean hasAzPosError() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double azPosError = 4;</code>
       */
      public double getAzPosError() {
        return azPosError_;
      }
      /**
       * <code>required double azPosError = 4;</code>
       */
      public Builder setAzPosError(double value) {
        bitField0_ |= 0x00000008;
        azPosError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double azPosError = 4;</code>
       */
      public Builder clearAzPosError() {
        bitField0_ = (bitField0_ & ~0x00000008);
        azPosError_ = 0D;
        onChanged();
        return this;
      }

      private boolean azInPosition_ ;
      /**
       * <code>required bool azInPosition = 5;</code>
       */
      public boolean hasAzInPosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool azInPosition = 5;</code>
       */
      public boolean getAzInPosition() {
        return azInPosition_;
      }
      /**
       * <code>required bool azInPosition = 5;</code>
       */
      public Builder setAzInPosition(boolean value) {
        bitField0_ |= 0x00000010;
        azInPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool azInPosition = 5;</code>
       */
      public Builder clearAzInPosition() {
        bitField0_ = (bitField0_ & ~0x00000010);
        azInPosition_ = false;
        onChanged();
        return this;
      }

      private double elPos_ ;
      /**
       * <code>required double elPos = 6;</code>
       */
      public boolean hasElPos() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required double elPos = 6;</code>
       */
      public double getElPos() {
        return elPos_;
      }
      /**
       * <code>required double elPos = 6;</code>
       */
      public Builder setElPos(double value) {
        bitField0_ |= 0x00000020;
        elPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elPos = 6;</code>
       */
      public Builder clearElPos() {
        bitField0_ = (bitField0_ & ~0x00000020);
        elPos_ = 0D;
        onChanged();
        return this;
      }

      private double elPosDemand_ ;
      /**
       * <code>required double elPosDemand = 7;</code>
       */
      public boolean hasElPosDemand() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double elPosDemand = 7;</code>
       */
      public double getElPosDemand() {
        return elPosDemand_;
      }
      /**
       * <code>required double elPosDemand = 7;</code>
       */
      public Builder setElPosDemand(double value) {
        bitField0_ |= 0x00000040;
        elPosDemand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elPosDemand = 7;</code>
       */
      public Builder clearElPosDemand() {
        bitField0_ = (bitField0_ & ~0x00000040);
        elPosDemand_ = 0D;
        onChanged();
        return this;
      }

      private double elPosError_ ;
      /**
       * <code>required double elPosError = 8;</code>
       */
      public boolean hasElPosError() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required double elPosError = 8;</code>
       */
      public double getElPosError() {
        return elPosError_;
      }
      /**
       * <code>required double elPosError = 8;</code>
       */
      public Builder setElPosError(double value) {
        bitField0_ |= 0x00000080;
        elPosError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elPosError = 8;</code>
       */
      public Builder clearElPosError() {
        bitField0_ = (bitField0_ & ~0x00000080);
        elPosError_ = 0D;
        onChanged();
        return this;
      }

      private boolean elInPosition_ ;
      /**
       * <code>required bool elInPosition = 9;</code>
       */
      public boolean hasElInPosition() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required bool elInPosition = 9;</code>
       */
      public boolean getElInPosition() {
        return elInPosition_;
      }
      /**
       * <code>required bool elInPosition = 9;</code>
       */
      public Builder setElInPosition(boolean value) {
        bitField0_ |= 0x00000100;
        elInPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool elInPosition = 9;</code>
       */
      public Builder clearElInPosition() {
        bitField0_ = (bitField0_ & ~0x00000100);
        elInPosition_ = false;
        onChanged();
        return this;
      }

      private double encodeLatchingTime_ ;
      /**
       * <code>required double encodeLatchingTime = 10;</code>
       */
      public boolean hasEncodeLatchingTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required double encodeLatchingTime = 10;</code>
       */
      public double getEncodeLatchingTime() {
        return encodeLatchingTime_;
      }
      /**
       * <code>required double encodeLatchingTime = 10;</code>
       */
      public Builder setEncodeLatchingTime(double value) {
        bitField0_ |= 0x00000200;
        encodeLatchingTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double encodeLatchingTime = 10;</code>
       */
      public Builder clearEncodeLatchingTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        encodeLatchingTime_ = 0D;
        onChanged();
        return this;
      }

      private int azPosDmdErrCount_ ;
      /**
       * <code>required int32 azPosDmdErrCount = 11;</code>
       */
      public boolean hasAzPosDmdErrCount() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 azPosDmdErrCount = 11;</code>
       */
      public int getAzPosDmdErrCount() {
        return azPosDmdErrCount_;
      }
      /**
       * <code>required int32 azPosDmdErrCount = 11;</code>
       */
      public Builder setAzPosDmdErrCount(int value) {
        bitField0_ |= 0x00000400;
        azPosDmdErrCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 azPosDmdErrCount = 11;</code>
       */
      public Builder clearAzPosDmdErrCount() {
        bitField0_ = (bitField0_ & ~0x00000400);
        azPosDmdErrCount_ = 0;
        onChanged();
        return this;
      }

      private int elPosDmdErrCount_ ;
      /**
       * <code>required int32 elPosDmdErrCount = 12;</code>
       */
      public boolean hasElPosDmdErrCount() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 elPosDmdErrCount = 12;</code>
       */
      public int getElPosDmdErrCount() {
        return elPosDmdErrCount_;
      }
      /**
       * <code>required int32 elPosDmdErrCount = 12;</code>
       */
      public Builder setElPosDmdErrCount(int value) {
        bitField0_ |= 0x00000800;
        elPosDmdErrCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 elPosDmdErrCount = 12;</code>
       */
      public Builder clearElPosDmdErrCount() {
        bitField0_ = (bitField0_ & ~0x00000800);
        elPosDmdErrCount_ = 0;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>required double time = 13;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required double time = 13;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 13;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00001000;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 13;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00001000);
        time_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eventpoc.McsCurrentPositionEvent)
    }

    static {
      defaultInstance = new McsCurrentPositionEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eventpoc.McsCurrentPositionEvent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventpoc_TcsPositionDemandEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventpoc_TcsPositionDemandEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventpoc_McsCurrentPositionEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eventpoc_McsCurrentPositionEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024tcs_mcs_events.proto\022\010eventpoc\"J\n\026TcsP" +
      "ositionDemandEvent\022\017\n\007azimuth\030\001 \002(\001\022\021\n\te" +
      "levation\030\002 \002(\001\022\014\n\004time\030\003 \002(\001\"\252\002\n\027McsCurr" +
      "entPositionEvent\022\025\n\rmcsInPosition\030\001 \002(\010\022" +
      "\r\n\005azPos\030\002 \002(\001\022\023\n\013azPosDemand\030\003 \002(\001\022\022\n\na" +
      "zPosError\030\004 \002(\001\022\024\n\014azInPosition\030\005 \002(\010\022\r\n" +
      "\005elPos\030\006 \002(\001\022\023\n\013elPosDemand\030\007 \002(\001\022\022\n\nelP" +
      "osError\030\010 \002(\001\022\024\n\014elInPosition\030\t \002(\010\022\032\n\022e" +
      "ncodeLatchingTime\030\n \002(\001\022\030\n\020azPosDmdErrCo" +
      "unt\030\013 \002(\005\022\030\n\020elPosDmdErrCount\030\014 \002(\005\022\014\n\004t",
      "ime\030\r \002(\001B,\n\026com.tmt.tcs.mcs.protosB\022Tcs" +
      "McsEventsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eventpoc_TcsPositionDemandEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventpoc_TcsPositionDemandEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventpoc_TcsPositionDemandEvent_descriptor,
        new java.lang.String[] { "Azimuth", "Elevation", "Time", });
    internal_static_eventpoc_McsCurrentPositionEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eventpoc_McsCurrentPositionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eventpoc_McsCurrentPositionEvent_descriptor,
        new java.lang.String[] { "McsInPosition", "AzPos", "AzPosDemand", "AzPosError", "AzInPosition", "ElPos", "ElPosDemand", "ElPosError", "ElInPosition", "EncodeLatchingTime", "AzPosDmdErrCount", "ElPosDmdErrCount", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
