// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcs_to_mcs_commands.proto

package com.tmt.tcs.mcs.protos;

public final class TcsToMcsCommandProtos {
  private TcsToMcsCommandProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code commandpoc.TransitionType}
   */
  public enum TransitionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYSTEMOFF = 0;</code>
     */
    SYSTEMOFF(0, 0),
    /**
     * <code>REBOOT = 1;</code>
     */
    REBOOT(1, 1),
    /**
     * <code>STARTUP = 2;</code>
     */
    STARTUP(2, 2),
    /**
     * <code>SHUTDOWN = 3;</code>
     */
    SHUTDOWN(3, 3),
    ;

    /**
     * <code>SYSTEMOFF = 0;</code>
     */
    public static final int SYSTEMOFF_VALUE = 0;
    /**
     * <code>REBOOT = 1;</code>
     */
    public static final int REBOOT_VALUE = 1;
    /**
     * <code>STARTUP = 2;</code>
     */
    public static final int STARTUP_VALUE = 2;
    /**
     * <code>SHUTDOWN = 3;</code>
     */
    public static final int SHUTDOWN_VALUE = 3;


    public final int getNumber() { return value; }

    public static TransitionType valueOf(int value) {
      switch (value) {
        case 0: return SYSTEMOFF;
        case 1: return REBOOT;
        case 2: return STARTUP;
        case 3: return SHUTDOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransitionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TransitionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransitionType>() {
            public TransitionType findValueByNumber(int number) {
              return TransitionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransitionType[] VALUES = values();

    public static TransitionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TransitionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:commandpoc.TransitionType)
  }

  /**
   * Protobuf enum {@code commandpoc.CmdError}
   */
  public enum CmdError
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ILLEGAL_STATE = 0;</code>
     */
    ILLEGAL_STATE(0, 0),
    /**
     * <code>BUSY = 1;</code>
     */
    BUSY(1, 1),
    /**
     * <code>OUT_OF_RANGE = 2;</code>
     */
    OUT_OF_RANGE(2, 2),
    /**
     * <code>OUT_OF_SPEC = 3;</code>
     */
    OUT_OF_SPEC(3, 3),
    /**
     * <code>FAILED = 4;</code>
     */
    FAILED(4, 4),
    ;

    /**
     * <code>ILLEGAL_STATE = 0;</code>
     */
    public static final int ILLEGAL_STATE_VALUE = 0;
    /**
     * <code>BUSY = 1;</code>
     */
    public static final int BUSY_VALUE = 1;
    /**
     * <code>OUT_OF_RANGE = 2;</code>
     */
    public static final int OUT_OF_RANGE_VALUE = 2;
    /**
     * <code>OUT_OF_SPEC = 3;</code>
     */
    public static final int OUT_OF_SPEC_VALUE = 3;
    /**
     * <code>FAILED = 4;</code>
     */
    public static final int FAILED_VALUE = 4;


    public final int getNumber() { return value; }

    public static CmdError valueOf(int value) {
      switch (value) {
        case 0: return ILLEGAL_STATE;
        case 1: return BUSY;
        case 2: return OUT_OF_RANGE;
        case 3: return OUT_OF_SPEC;
        case 4: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdError>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdError>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdError>() {
            public CmdError findValueByNumber(int number) {
              return CmdError.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final CmdError[] VALUES = values();

    public static CmdError valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CmdError(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:commandpoc.CmdError)
  }

  public interface LifeCycleCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:commandpoc.LifeCycleCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
     */
    boolean hasTransitionType();
    /**
     * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
     */
    com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType getTransitionType();
  }
  /**
   * Protobuf type {@code commandpoc.LifeCycleCommand}
   */
  public static final class LifeCycleCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:commandpoc.LifeCycleCommand)
      LifeCycleCommandOrBuilder {
    // Use LifeCycleCommand.newBuilder() to construct.
    private LifeCycleCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LifeCycleCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LifeCycleCommand defaultInstance;
    public static LifeCycleCommand getDefaultInstance() {
      return defaultInstance;
    }

    public LifeCycleCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LifeCycleCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType value = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                transitionType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_LifeCycleCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_LifeCycleCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<LifeCycleCommand> PARSER =
        new com.google.protobuf.AbstractParser<LifeCycleCommand>() {
      public LifeCycleCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LifeCycleCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LifeCycleCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRANSITIONTYPE_FIELD_NUMBER = 1;
    private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType transitionType_;
    /**
     * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
     */
    public boolean hasTransitionType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
     */
    public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType getTransitionType() {
      return transitionType_;
    }

    private void initFields() {
      transitionType_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType.STARTUP;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTransitionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, transitionType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, transitionType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code commandpoc.LifeCycleCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:commandpoc.LifeCycleCommand)
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_LifeCycleCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_LifeCycleCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.Builder.class);
      }

      // Construct using com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        transitionType_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType.STARTUP;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_LifeCycleCommand_descriptor;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand getDefaultInstanceForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.getDefaultInstance();
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand build() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand buildPartial() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand result = new com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.transitionType_ = transitionType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand) {
          return mergeFrom((com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand other) {
        if (other == com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand.getDefaultInstance()) return this;
        if (other.hasTransitionType()) {
          setTransitionType(other.getTransitionType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTransitionType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.LifeCycleCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType transitionType_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType.STARTUP;
      /**
       * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
       */
      public boolean hasTransitionType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
       */
      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType getTransitionType() {
        return transitionType_;
      }
      /**
       * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
       */
      public Builder setTransitionType(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        transitionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .commandpoc.TransitionType transitionType = 1 [default = STARTUP];</code>
       */
      public Builder clearTransitionType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transitionType_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.TransitionType.STARTUP;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:commandpoc.LifeCycleCommand)
    }

    static {
      defaultInstance = new LifeCycleCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:commandpoc.LifeCycleCommand)
  }

  public interface FollowCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:commandpoc.FollowCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
     */
    boolean hasAxes();
    /**
     * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
     */
    com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes getAxes();
  }
  /**
   * Protobuf type {@code commandpoc.FollowCommand}
   */
  public static final class FollowCommand extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:commandpoc.FollowCommand)
      FollowCommandOrBuilder {
    // Use FollowCommand.newBuilder() to construct.
    private FollowCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FollowCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FollowCommand defaultInstance;
    public static FollowCommand getDefaultInstance() {
      return defaultInstance;
    }

    public FollowCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FollowCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes value = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                axes_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_FollowCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_FollowCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<FollowCommand> PARSER =
        new com.google.protobuf.AbstractParser<FollowCommand>() {
      public FollowCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FollowCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FollowCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code commandpoc.FollowCommand.Axes}
     */
    public enum Axes
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AZ = 0;</code>
       */
      AZ(0, 0),
      /**
       * <code>EL = 1;</code>
       */
      EL(1, 1),
      /**
       * <code>BOTH = 2;</code>
       */
      BOTH(2, 2),
      ;

      /**
       * <code>AZ = 0;</code>
       */
      public static final int AZ_VALUE = 0;
      /**
       * <code>EL = 1;</code>
       */
      public static final int EL_VALUE = 1;
      /**
       * <code>BOTH = 2;</code>
       */
      public static final int BOTH_VALUE = 2;


      public final int getNumber() { return value; }

      public static Axes valueOf(int value) {
        switch (value) {
          case 0: return AZ;
          case 1: return EL;
          case 2: return BOTH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Axes>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Axes>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Axes>() {
              public Axes findValueByNumber(int number) {
                return Axes.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final Axes[] VALUES = values();

      public static Axes valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Axes(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:commandpoc.FollowCommand.Axes)
    }

    private int bitField0_;
    public static final int AXES_FIELD_NUMBER = 1;
    private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes axes_;
    /**
     * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
     */
    public boolean hasAxes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
     */
    public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes getAxes() {
      return axes_;
    }

    private void initFields() {
      axes_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes.BOTH;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAxes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, axes_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, axes_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code commandpoc.FollowCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:commandpoc.FollowCommand)
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_FollowCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_FollowCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Builder.class);
      }

      // Construct using com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        axes_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes.BOTH;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_FollowCommand_descriptor;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand getDefaultInstanceForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.getDefaultInstance();
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand build() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand buildPartial() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand result = new com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.axes_ = axes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand) {
          return mergeFrom((com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand other) {
        if (other == com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.getDefaultInstance()) return this;
        if (other.hasAxes()) {
          setAxes(other.getAxes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAxes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes axes_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes.BOTH;
      /**
       * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
       */
      public boolean hasAxes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
       */
      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes getAxes() {
        return axes_;
      }
      /**
       * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
       */
      public Builder setAxes(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        axes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .commandpoc.FollowCommand.Axes axes = 1 [default = BOTH];</code>
       */
      public Builder clearAxes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        axes_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.FollowCommand.Axes.BOTH;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:commandpoc.FollowCommand)
    }

    static {
      defaultInstance = new FollowCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:commandpoc.FollowCommand)
  }

  public interface CommandResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:commandpoc.CommandResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    boolean hasErrorState();
    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    java.lang.String getErrorState();
    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    com.google.protobuf.ByteString
        getErrorStateBytes();

    /**
     * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
     */
    boolean hasCmdError();
    /**
     * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
     */
    com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError getCmdError();

    /**
     * <code>required string error_info = 3;</code>
     */
    boolean hasErrorInfo();
    /**
     * <code>required string error_info = 3;</code>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>required string error_info = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>required double time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 4;</code>
     */
    double getTime();
  }
  /**
   * Protobuf type {@code commandpoc.CommandResponse}
   */
  public static final class CommandResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:commandpoc.CommandResponse)
      CommandResponseOrBuilder {
    // Use CommandResponse.newBuilder() to construct.
    private CommandResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommandResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommandResponse defaultInstance;
    public static CommandResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CommandResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommandResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              errorState_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError value = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                cmdError_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errorInfo_ = bs;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              time_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_CommandResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_CommandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CommandResponse> PARSER =
        new com.google.protobuf.AbstractParser<CommandResponse>() {
      public CommandResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommandResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERROR_STATE_FIELD_NUMBER = 1;
    private java.lang.Object errorState_;
    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    public boolean hasErrorState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    public java.lang.String getErrorState() {
      java.lang.Object ref = errorState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorState_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string error_state = 1 [default = "OK"];</code>
     */
    public com.google.protobuf.ByteString
        getErrorStateBytes() {
      java.lang.Object ref = errorState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_ERROR_FIELD_NUMBER = 2;
    private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError cmdError_;
    /**
     * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
     */
    public boolean hasCmdError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
     */
    public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError getCmdError() {
      return cmdError_;
    }

    public static final int ERROR_INFO_FIELD_NUMBER = 3;
    private java.lang.Object errorInfo_;
    /**
     * <code>required string error_info = 3;</code>
     */
    public boolean hasErrorInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string error_info = 3;</code>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string error_info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private double time_;
    /**
     * <code>required double time = 4;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double time = 4;</code>
     */
    public double getTime() {
      return time_;
    }

    private void initFields() {
      errorState_ = "OK";
      cmdError_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError.BUSY;
      errorInfo_ = "";
      time_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrorState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorStateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, cmdError_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorStateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmdError_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code commandpoc.CommandResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:commandpoc.CommandResponse)
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_CommandResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_CommandResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.class, com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.Builder.class);
      }

      // Construct using com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorState_ = "OK";
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdError_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError.BUSY;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.internal_static_commandpoc_CommandResponse_descriptor;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse getDefaultInstanceForType() {
        return com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.getDefaultInstance();
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse build() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse buildPartial() {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse result = new com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorState_ = errorState_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdError_ = cmdError_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorInfo_ = errorInfo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse) {
          return mergeFrom((com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse other) {
        if (other == com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse.getDefaultInstance()) return this;
        if (other.hasErrorState()) {
          bitField0_ |= 0x00000001;
          errorState_ = other.errorState_;
          onChanged();
        }
        if (other.hasCmdError()) {
          setCmdError(other.getCmdError());
        }
        if (other.hasErrorInfo()) {
          bitField0_ |= 0x00000004;
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorState()) {
          
          return false;
        }
        if (!hasCmdError()) {
          
          return false;
        }
        if (!hasErrorInfo()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CommandResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorState_ = "OK";
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public boolean hasErrorState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public java.lang.String getErrorState() {
        java.lang.Object ref = errorState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorState_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public com.google.protobuf.ByteString
          getErrorStateBytes() {
        java.lang.Object ref = errorState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public Builder setErrorState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public Builder clearErrorState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorState_ = getDefaultInstance().getErrorState();
        onChanged();
        return this;
      }
      /**
       * <code>required string error_state = 1 [default = "OK"];</code>
       */
      public Builder setErrorStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorState_ = value;
        onChanged();
        return this;
      }

      private com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError cmdError_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError.BUSY;
      /**
       * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
       */
      public boolean hasCmdError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
       */
      public com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError getCmdError() {
        return cmdError_;
      }
      /**
       * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
       */
      public Builder setCmdError(com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        cmdError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .commandpoc.CmdError cmd_error = 2 [default = BUSY];</code>
       */
      public Builder clearCmdError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdError_ = com.tmt.tcs.mcs.protos.TcsToMcsCommandProtos.CmdError.BUSY;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>required string error_info = 3;</code>
       */
      public boolean hasErrorInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string error_info = 3;</code>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string error_info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string error_info = 3;</code>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string error_info = 3;</code>
       */
      public Builder clearErrorInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>required string error_info = 3;</code>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>required double time = 4;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double time = 4;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 4;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:commandpoc.CommandResponse)
    }

    static {
      defaultInstance = new CommandResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:commandpoc.CommandResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commandpoc_LifeCycleCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commandpoc_LifeCycleCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commandpoc_FollowCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commandpoc_FollowCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commandpoc_CommandResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commandpoc_CommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031tcs_to_mcs_commands.proto\022\ncommandpoc\"" +
      "O\n\020LifeCycleCommand\022;\n\016transitionType\030\001 " +
      "\002(\0162\032.commandpoc.TransitionType:\007STARTUP" +
      "\"e\n\rFollowCommand\0222\n\004axes\030\001 \002(\0162\036.comman" +
      "dpoc.FollowCommand.Axes:\004BOTH\" \n\004Axes\022\006\n" +
      "\002AZ\020\000\022\006\n\002EL\020\001\022\010\n\004BOTH\020\002\"{\n\017CommandRespon" +
      "se\022\027\n\013error_state\030\001 \002(\t:\002OK\022-\n\tcmd_error" +
      "\030\002 \002(\0162\024.commandpoc.CmdError:\004BUSY\022\022\n\ner" +
      "ror_info\030\003 \002(\t\022\014\n\004time\030\004 \002(\001*F\n\016Transiti" +
      "onType\022\r\n\tSYSTEMOFF\020\000\022\n\n\006REBOOT\020\001\022\013\n\007STA",
      "RTUP\020\002\022\014\n\010SHUTDOWN\020\003*V\n\010CmdError\022\021\n\rILLE" +
      "GAL_STATE\020\000\022\010\n\004BUSY\020\001\022\020\n\014OUT_OF_RANGE\020\002\022" +
      "\017\n\013OUT_OF_SPEC\020\003\022\n\n\006FAILED\020\004B/\n\026com.tmt." +
      "tcs.mcs.protosB\025TcsToMcsCommandProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_commandpoc_LifeCycleCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_commandpoc_LifeCycleCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commandpoc_LifeCycleCommand_descriptor,
        new java.lang.String[] { "TransitionType", });
    internal_static_commandpoc_FollowCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_commandpoc_FollowCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commandpoc_FollowCommand_descriptor,
        new java.lang.String[] { "Axes", });
    internal_static_commandpoc_CommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_commandpoc_CommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commandpoc_CommandResponse_descriptor,
        new java.lang.String[] { "ErrorState", "CmdError", "ErrorInfo", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
